### PR TITLE
chore: drop node 4 support

### PR DESCRIPTION
**Pull request by DominicKramer**
BREAKING CHANGE:

### CODE REVIEW

**Comment by ofrobots** [comment]
Where be the nits?

**Comment by DominicKramer** [comment]
I'm not sure why the `ci/circleci: node4` check is still trying to be run.  @JustinBeckwith have you encountered this when you changed the other repos?

**Comment by JustinBeckwith** [comment]
Fixed!

**Comment by DominicKramer** [comment]
@JustinBeckwith thanks.  Before I land this, what are your nits?

**Comment by JustinBeckwith** [comment]
Oh gosh, sorry.  No nits 🤣

**Comment by DominicKramer** [comment]
@JustinBeckwith no worries.

**Pull request merged**
