### PR TITLE
fix: expose express middleware, add system-test

### PR DESCRIPTION
**Pull request by ofrobots**
The express middleware was previously not publicly exposed; do so.
Also add a system-test to validate the behaviour.

### CODE REVIEW

**Comment by ofrobots** [comment]
@JustinBeckwith the docs job failure seems like a linkinator bug.

**Comment by JustinBeckwith** [comment]
Yeah, so taking a look - "bug" is a strong word :) This url, as of now, is a 404:
https://raw.githubusercontent.com/googleapis/nodejs-logging-winston/master/doc/images/request-bundling.png

Not sure what the right way to handle this is!  We could:
a.) Ignore the error and hammer this in, knowing that it will exist after the PR lands
b.) Create a commit that adds the image first, then this one
c.) Try to do some bespoke thing specific to github 

Any thoughts on how y'all think this should go?

**Comment by ofrobots** [comment]
Hammer is least effort, let's go with that.

**Comment by JustinBeckwith** [comment]
SGTM

**Comment by ofrobots** [comment]
The post install check was finding a legitimate failure when the module is used with `winston@2`. I had to water down some of the declared types to make things work with both `winston@2` and `winston@3`.

**Comment by ofrobots** [comment]
Post install is continuing to find legitimate problems.

```
node_modules/@google-cloud/logging-winston/build/src/middleware/express.d.ts:27:21 - error TS2694: Namespace 'winston' has no exported member 'Logger'.

27     logger: winston.Logger;
```

I thought I had addressed this by removing the manual type definition for the return type for `middleware` function. It turns out that the compiler will generate an explicit type anyway.

I don't see a way to emit proper types and support both winston@2 and winston@3 with the same module.

The only option I see is to drop support for winston@2 in a semver major.

**Comment by DominicKramer** [comment]
@ofrobots Let me know whenever you want another review of this.  Thanks.

**Comment by ofrobots** [comment]
Had to drop `require-inject` and replace it with `proxyquire` because of this issue: https://gist.github.com/ofrobots/06270fe3f65ea93a4bda1a13348d8400

**Comment by ofrobots** [comment]
@JustinBeckwith @bcoe I need an admin to land this. The docs failure is a known limitation of the docs test.

**Pull request merged**
