### PR TITLE
fix: run tests with source map support

### PR DESCRIPTION
**Pull request by ofrobots**

### CODE REVIEW

**Comment by ofrobots** [comment]
Samples are all un-transpiled. Why do they need source-map-support?

**Comment by DominicKramer** [comment]
@ofrobots I was thinking that if there was a failure in the samples tests that was caused by an error being thrown in the underlying logging winston code, then source-map-support would translate the `js` stacktrace to the corresponding `ts` files to make debugging easier when reading the stacktrace from the CI's output.

**Comment by ofrobots** [comment]
@DominicKramer that's a fair point. Added. Will land once/if CI passes.

**Comment by DominicKramer** [comment]
@ofrobots Sounds good.

**Pull request merged**
