### PR TITLE
Winston 3 support

### LINKED ISSUE #84: winston 3.0.0 support
Hi guys, first of all thanks for your amazing work !

Since winston 3.0.0 is being in RC and is planned to be released by the end of this month, I'd like to know what are your plans regarding this new release and the compatibility with your package ?

Thanks in advance for your answers ;)

### PR DESCRIPTION
**Pull request by kazazes**
Fixes #84, with two tests failing. Hopefully a maintainer can create a 3.0 dev branch and provide some guidance on the failing cases.

- [ ] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by kazazes** [comment]
I signed it!

**Comment by ofrobots** [comment]
@kazazes thanks a lot for the PR! 🍰

One question we need to figure out the answer to is whether we should drop support for `winston@2` at this point or continue to transparently – or non-transparently – supporting both `winston@2` and `winston@3`.

**Comment by kazazes** [comment]
@ofrobots a runtime check could work, the instantiation options for the transport haven’t changed.

My experience with peerDependencies is limited, but would bumping the Winston and library versions keep winston@2 users on the current, and ^3 on a future release?

**Comment by typesafe** [comment]
@kazazes I'm afraid runtime checks won't work for typescript. @ofrobots this also means supporting both versions _transparently_ won't be possible. 

My 2 cents... I don't see why supporting both versions would be necessary. Introducing this depency typically happens early in a project along with winston et. al., when setting things up. 
The only reason for keeping v2 support is for scenarios where stackdriver gets introduced in an existing project aleeady using winston v2. When that happens, I think the little extra effort to migrqte the winston v2 client code won't hold anybody back from doing it...

**Comment by soldair** [comment]
I have a branch with run time checks that's almost ready it should work nice for users with either version. hope to land it soon and thanks so much to @kazazes for the work on this version. it really helped out.

@kazazes if you want to take a look =) https://github.com/soldair/nodejs-logging-winston

**Comment by typesafe** [comment]
@soldair I still think typescript won't be (entirely) happy with this. Won't it complain about type `(LoggingWinston2 | LoggingWinston3)` not being compatible with either `TransportStream` or `winston.Transport`, depending on which winston version you are using?

**Comment by ofrobots** [comment]
@kazazes thank you very much for the PR. We shipped `winston@3` support in 0.10.0 via #161 and `winston@2` is still supported. Please give it a shot. I am going to close this issue, but please add a comment if there are issues that remain unaddressed.

**Pull request closed without merging**
