### PR TITLE
chore(package): upgrade logging dep

### PR DESCRIPTION
**Pull request by ofrobots**
Fixes: https://github.com/googleapis/nodejs-logging-winston/issues/57

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by ofrobots** [comment]
@alexander-fenster @DominicKramer  any idea why the docs CI is croaking here?

**Comment by alexander-fenster** [comment]
CI bug. Sometimes `node_modules/.bin/repo_tools` is created as non-executable. Happens only in Circle, and I could never reproduce it. Restart always helps.

**Comment by ofrobots** [comment]
Flaky tests are arguably worse than no tests. Can we get this fixed? (where should I open the tracking bug?)

@DominicKramer any idea why the Windows build is failing with a type-error?

**Comment by ofrobots** [comment]
Succeeded on a re-run. This needs a review. @DominicKramer PTAL.

**Pull request merged**
