### PR TITLE
3102:nodejs-logging-winston: Convert samples test from ava to mocha

### PR DESCRIPTION
**Pull request by nareshqlogic**
Fixes convert all sample tests from ava to mocha #2865(https://github.com/googleapis/google-cloud-node/issues/2865) (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@DominicKramer this is part of a broad effort to use mocha consistently for all of our tests.  This is mine :)

**Comment by DominicKramer** [comment]
@JustinBeckwith sounds good :+1:

**Comment by nareshqlogic** [comment]
@DominicKramer  Thank you for suggestion I will add the description.

**Comment by JustinBeckwith** [comment]
After the system tests are passing, I'm happy to merge!

**Comment by DominicKramer** [comment]
I think the system test errors are independent of this PR.  PR #212 fixes part of the system system tests.  I am also working on another PR that fixes the installation tests.  When those land, and you rebase, the system tests should pass on this PR.

**Pull request merged**
