### PR TITLE
chore: remove unnecessary runtime dependencies

### PR DESCRIPTION
**Pull request by JustinBeckwith**
So it's entirely possible I'm missing something.  But at a glance...  it doesn't look like you actually need `google-cloud/common` in this module 🤷‍♂️

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Oh my.  At a second glance, I see a bunch of things that could be moved from dependencies over to devDependencies too.

**Comment by JustinBeckwith** [comment]
I have no clue what's up with the lint failure.... any ideas?

**Comment by alexander-fenster** [comment]
Update `samples/package-lock.json` as well. Do this:
```sh
rm -rf samples/node_modules
npm link
cd samples
npm link ../
npm install
cd ..
git add samples/package-lock.json
git commit -m 'make linter happy'
```

**Comment by alexander-fenster** [comment]
(note: I have just edited the commands above)

**Comment by JustinBeckwith** [comment]
Thank you :)

**Pull request merged**
